# spring:
#   application: config-default

 # spring:
#   config:
#     import: configserver:
spring:
  application: config-default

  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # You can set this to "create-drop", "create", "update", or "none" based on your requirements
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


    
eurekha:
  instance: 
     hostname: localhost 
